G+C ratio, file name handling in seqstats
biogo/examples pull request #6
Opened 2017-08-16 12:50 UTC by aboffin

@kortschak, I added G+C ratio to the list of DNA sequence statistics printed by seqstats, in addition, I used TrimSuffix instead of Split to handle file names of the form "a.b.c.d.ext" (the older version would just print "a", while the newer version correctly prints "a.b.c.d").

2017-08-18 01:48 UTC, kortschak requested changes

2017-08-18 01:48 UTC, kortschak commented on seqstats/seqstats.go
> +	var ctr = map[string]int{"G": 0, "C": 0}
Please make this `var ctr [256]int`.

2017-08-18 01:48 UTC, kortschak commented on seqstats/seqstats.go
> +		seqstr = s.(*linear.Seq).Seq.String()
```
for _, l := range s.(*linear.Seq).Seq {
    ctr[l|' ']++ // Count lowercased letter.
}
```

2017-08-18 01:48 UTC, kortschak commented on seqstats/seqstats.go
> +	b.perGC = float64(ctr["G"]+ctr["C"]) / float64(b.size) * 100
This is not formally correct for genomes with ambiguous letters. The denominator should be `float64(ctr['a']+ctr['c']+ctr['g']+ctr['t'])`.

2017-08-18 08:50 UTC, aboffin commented
@kortschak, Thank you, I have incorporated the requested changes.

2017-09-12 08:02 UTC, aboffin reviewed
@kortschak Is there anything else that's needed for this to be committed? Thank you.

2017-09-12 11:00 UTC, kortschak approved these changes

2017-09-12 11:01 UTC, merged

2017-09-12 11:01 UTC, kortschak commented
Sorry. That fell off the list.